apiVersion: shardingsphere.sphere-ex.com/v1alpha1
kind: Proxy
metadata:
  name: proxy-sample
spec:
  version: "5.1.2"
  serviceType:
    type: ClusterIP
  replicas: 1
  proxyConfigName: "proxyconfig-sample"
  port: 3307
  mySQLDriver:
    version: "5.1.47"
  resources:
    limits:
      cpu: "2"
      memory: "2Gi"
    requests:
      cpu: "0.2"
      memory: "1.6Gi"
