apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webhook.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: "webhook"
  selector:
    app: shardingsphere-operator
