---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-shardingsphere-sphere-ex-com-v1alpha1-proxy
  failurePolicy: Fail
  name: mproxy.kb.io
  rules:
  - apiGroups:
    - shardingsphere.sphere-ex.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - proxies
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-shardingsphere-sphere-ex-com-v1alpha1-proxy
  failurePolicy: Fail
  name: vproxy.kb.io
  rules:
  - apiGroups:
    - shardingsphere.sphere-ex.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - proxies
  sideEffects: None
