#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

## @section Name parameters
## @param nameOverride String to partially override common.names.fullname template (will maintain the release name)
##
nameOverride: shardingsphere-proxy

## @section ShardingSphere operator parameters
operator:
  ## @param replicaCount operator replica count
  ##
  replicaCount: 1
  image:
    ## @param image.repository operator image name
    ##
    repository: "apache/shardingsphere-operator"
    ## @param image.pullPolicy image pull policy
    ##
    pullPolicy: IfNotPresent
    ## @param image.tag image tag
    ##
    tag: "0.3.0"
  ## @param imagePullSecrets image pull secret of private repository
  ## e.g:
  ## imagePullSecrets:
  ##   - name: mysecret
  ##
  imagePullSecrets: [ ]
  ## @param resources operator Resources required by the operator
  ## e.g:
  ## resources:
  ##   limits:
  ##     cpu: 2
  ##   limits:
  ##     cpu: 2
  ##
  resources: { }
  ## @param health.healthProbePort operator health check port
  ##
  health:
    healthProbePort: 8080
  ## @param metrics.metricsBindAddress operator metrics port
  ##
  metrics:
    metricsBindAddress: 9090 
  ## @param featureGates.computeNode operator health check port
  ## @param featureGates.storageNode operator health check port
  ##
  featureGates:
    computeNode: false
    storageNode: false
    chaos: false

  storageNodeProviders:
    aws:
      ## @param storageNodeProviders.aws.enabled Whether to enable aws storage node
      ## @param storageNodeProviders.aws.region aws region
      ## @param storageNodeProviders.aws.accessKeyId aws access key id
      ## @param storageNodeProviders.aws.secretAccessKey aws secret access key
      ##
      enabled: false
      region: ""
      accessKeyId: ""
      secretAccessKey: ""
