# Default values for proxy-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: "shardingsphere-operator"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.1"
imagePullSecrets: []
service:
  type: ClusterIP
  port: 80
resources:
   requests:
     cpu: 100m
     memory: 128Mi
webhook:
  serviceName: shardingsphere-operator-admission-webhook
  port: 9443
health:
  healthProbePort: 8081

serviceAccount:
  name: shardingsphere-operator