# permissions for end users to view proxyconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxyconfig-viewer-role
rules:
- apiGroups:
  - sphere-ex.com.sphere-ex.com
  resources:
  - proxyconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sphere-ex.com.sphere-ex.com
  resources:
  - proxyconfigs/status
  verbs:
  - get
