---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmap
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployment/status
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shardingsphere.sphere-ex.com
  resources:
  - proxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shardingsphere.sphere-ex.com
  resources:
  - proxies/finalizers
  verbs:
  - update
- apiGroups:
  - shardingsphere.sphere-ex.com
  resources:
  - proxies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - shardingsphere.sphere-ex.com
  resources:
  - proxyconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shardingsphere.sphere-ex.com
  resources:
  - proxyconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - shardingsphere.sphere-ex.com
  resources:
  - proxyconfigs/status
  verbs:
  - get
  - patch
  - update
