apiVersion: shardingsphere.sphere-ex.com/v1alpha1
kind: Proxy
metadata:
  name: proxy-sample
spec:
  version: "5.1.0"
  serviceType:
    type: NodePort
    nodePort: 32001
  replicas: 2
  proxyConfigName: "sharding-proxy"
  port: 3308
  mySQLDriver:
    version: "5.1.47"
  resources:
    limits:
      cpu: "2"
      memory: "2Gi"
    requests:
      cpu: "0.2"
      memory: "1.6Gi"
  livenessProbe:
    tcpSocket:
      port: 3308
    periodSeconds: 10
  readinessProbe:
    tcpSocket:
      port: 3308
    periodSeconds: 20
  startupProbe:
    tcpSocket:
      port: 3308
    periodSeconds: 5
    failureThreshold: 12
