apiVersion: sphere-ex.com.sphere-ex.com/v1alpha1
kind: Proxy
metadata:
  name: proxy-sample
spec:
  version: "5.1.0"
  serviceType:
    type: ClusterIP
  replicas: 1
  mode: Cluster
  proxyConfigName: "sharding-proxy"
  mySQLDriver:
    version: "5.1.47"
  resource:
    limits:
      cpu: "2"
      memory: "2Gi"
    requests:
      cpu: "0.2"
      memory: "1.6Gi"

