baseURL = "https://shardingsphere.apache.org/oncloud/current/"
canonifyurls = true
languageCode = "en-us"
title = "ShardingSphere-On-Cloud"
theme = "hugo-theme-learn"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= true

[Languages]
[Languages.en]
#baseURL = "https://shardingsphere.apache.org/oncloud/current/"
title = "ShardingSphereOnCloud"
weight = 1
languageName = "English"

[Languages.cn]
#baseURL = "https://shardingsphere.apache.org/oncloud/current/"
title = "ShardingSphereOnCloud"
weight = 2
languageName = "简体中文"

[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
themeVariant = "white"
# Disable search function. It will hide search bar
disableSearch = false
editURL = "https://github.com/apache/shardingsphere-on-cloud/tree/master/docs/content/"
# Hide Next and Previous page buttons normally displayed full height beside content
disableNextPrev = true
# Hide breadcrumbs in the header and only show the current page title
disableBreadcrumb = true

[markup]
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
